services:
  postgres:
    image: 'postgres:16.2-alpine3.18'
    env_file:
      - .env
    container_name: postgres
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
